Always try to refresh the user info on local password login
ubuntu/authd-oidc-brokers pull request #171
Opened 2024-10-09 21:56 UTC by adombeck

Closes #520

2024-10-10 08:53 UTC, didrocks commented
Thanks for fixing this! I will let Denison/Marco doing the complete review.

Just a note on the test. There is an existing impact tests where you refreshed the golden file. However "Successfully authenticate user with password/First Call" isn’t really reflecting the issue at hands (even if we see it’s impacted, but I think it should not).

My advice would be that we ensure we have tests with the Provider mock to ensure we don’t regress in the future and my feeling is that it’s the right time to get those  groups tests. Some of them are probably already available, we just need to ensure they are titled explicitly enough. On the top of my head I can think of (all under `TestAuthenticate/`) tests along those lines:
- "Refresh groups with oidc auth"
- "Refresh groups with local password"
- "Refresh groups with local password if group endpoint accessible even if oidc is not reachable"
- "Keep older groups with oidc auth if groups endpoint is not accessible with oidc is reachable" (meaning: we still allow successful authentication)
- - "Keep older groups with local password if groups endpoint is not accessible with oidc is reachable" (meaning: we still allow successful authentication)
- "Keep older groups with local password if groups endpoint nor oidc is reachable"  (meaning: we still allow successful authentication, this is the full "offline mode")

That way we would test the matrix of oidc / groups endpoints reachable/not reachable and document how we behave regarding groups and various authentication modes.

Note: the behaviour of "we still allow to authenticate even if we can’t reach groups" is based on my memory on what we agreed about some weeks ago on MM.

2024-10-10 14:08 UTC, adombeck commented
> My advice would be that we ensure we have tests with the Provider mock to ensure we don’t regress in the future and my feeling is that it’s the right time to get those groups tests.

I'm fine with adding tests which test the refreshing of the user info, but I would like to do that in a follow-up, because I'm trying to get https://github.com/ubuntu/authd-oidc-brokers/pull/134 merged and want to base that on this change because I think it will simplify the tests. If I add the tests here, that will cause painful merge conflicts with that PR.

2024-10-10 14:09 UTC, adombeck commented
> I'm fine with adding tests which test the refreshing of the user info, but I would like to do that in a follow-up

If you're fine with that, I'll create an issue to track that follow-up work

2024-10-10 14:11 UTC, didrocks commented
> If you're fine with that, I'll create an issue to track that follow-up work

Yeah! If this is simpler, let’s go for it.

My only request is that it’s tracked and the tests are here before we publish to stable this change (to avoid another regression on it) :)

2024-10-11 11:41 UTC, denisonbarbosa requested changes
Looks good, but I have two comments (one of them is part of the review comments) and one question:

1) We are still missing a PR description;
2) Did you test this with a user that had cached information? What happens in this case?

2024-10-11 11:57 UTC, adombeck commented
> 1) We are still missing a PR description;

I added another paragraph to the commit message and copied it to the PR description. I will remove it from the merge commit message though, because I see no benefit in duplicating that explanation in the git history.

2024-10-11 11:57 UTC, adombeck commented on internal/broker/broker.go
> +			slog.Warn(fmt.Sprintf("Could not fetch user info: %v", err))
done

2024-10-11 12:03 UTC, adombeck commented
> 2) Did you test this with a user that had cached information? What happens in this case?

Yes, I tested it with a user that has cached information. I checked that the user's groups are updated when fetching the user info is successful. If fetching the user info is not successful (because there is no network connection), then the user can still log in but the groups are not updated.

2024-10-11 12:09 UTC, denisonbarbosa commented
> I added another paragraph to the commit message and copied it to the PR description. I will remove it from the merge commit message though, because I see no benefit in duplicating that explanation in the git history.

Maybe I'm wrong, but I feel like it's more important to have the rationale in the merge commit message than in an individual commit, no? This way, we can have the commit messages more focused on answering the "what" question and have the PR description (which is the merge commit message) focused on the "why".

2024-10-11 12:11 UTC, denisonbarbosa approved these changes
Looks good to me. Nice work!

2024-10-11 12:22 UTC, adombeck commented
> Maybe I'm wrong, but I feel like it's more important to have the rationale in the merge commit message than in an individual commit, no? This way, we can have the commit messages more focused on answering the "what" question and have the PR description (which is the merge commit message) focused on the "why".

Mmh I feel different about that. Why should we separate the "why" explanation from the actual commit? Personally, I see no benefit in the merge commit beside maybe linking to GitHub and Jira issues and the PR (done automatically by GitHub, but you can also get that from any commit in the PR by opening `https://github.com/ubuntu/authd/commit/$ID`, which shows the branches and PRs that the commit is in).

When I look at the source code and wonder why something is done the way it is, I run `git blame` or `git log -p` and look up which commit introduced it. That does not list merge commits. If I have to look up the merge commit for the change, that's one more step which I think is unnecessary. What do you think?

2024-10-11 12:24 UTC, merged